# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello1": "00_core.ipynb"}

modules = ["core1.py"]

doc_url = "https://fastai.github.io/nbdev_template1/"

git_url = "https://github.com/fastai/nbdev_template1/tree/master/"

def custom_doc_links(name): return None
